server {
    listen 80;
    server_name localhost;

    root /usr/share/nginx/html;
    index index.html;

    # FORÇA O MIME TYPE PARA .MJS (Cura o erro application/octet-stream)
    include /etc/nginx/mime.types; # Garante os tipos padrão
    types {
        application/javascript mjs;
    }

    # Adicionado mjs na compressão Gzip
    gzip on;
    gzip_types text/plain text/css application/json application/javascript text/javascript text/xml application/xml application/xml+rss;

    location / {
        try_files $uri $uri/ /index.html;
    }

    # Atualizado para incluir mjs no cache de 1 ano
    location ~* \.(js|mjs|css|png|jpg|jpeg|gif|ico|svg)$ {
        expires 1y;
        add_header Cache-Control "public, no-transform";
    }

    error_page 500 502 503 504 /50x.html;
    location = /50x.html {
        root /usr/share/nginx/html;
    }
}